apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-prod
  template:
    metadata:
      labels:
        app: redis-prod
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-prod
spec:
  selector:
    app: redis-prod
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
