apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devix-staging
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - api-staging.devix.app
      secretName: devix-staging-tls
  rules:
    - host: api-staging.devix.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devix-backend-staging
                port:
                  number: 80
