apiVersion: apps/v1
kind: Deployment
metadata:
  name: devix-backend-staging
  labels:
    app: devix-backend-staging
spec:
  selector:
    matchLabels:
      app: devix-backend-staging
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: devix-backend-staging
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: devix-backend-staging
                topologyKey: kubernetes.io/hostname
      containers:
        - name: backend
          image: riteshsingh193/devix-staging:384ca6556cf2320dedb3d1eaae6951098b9b7807
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: devix-staging-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: devix-backend-staging
spec:
  selector:
    app: devix-backend-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
