apiVersion: apps/v1
kind: Deployment
metadata:
  name: devix-backend-staging
  labels:
    app: devix-backend-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devix-backend-staging
  template:
    metadata:
      labels:
        app: devix-backend-staging
    spec:
      containers:
        - name: backend
          image: riteshsingh193/devix-staging:384ca6556cf2320dedb3d1eaae6951098b9b7807
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: devix-staging-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: devix-backend-staging
spec:
  selector:
    app: devix-backend-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
