apiVersion: apps/v1
kind: Deployment
metadata:
  name: devix
  labels:
    app: devix
spec:
  replicas: 5
  selector:
    matchLabels:
      app: devix
  template:
    metadata:
      labels:
        app: devix
    spec:
      containers:
        - name: devix
          image: ghcr.io/neutron420/devix-backend/devix:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: devix-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred
