apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-prod
spec:
  serviceName: "elasticsearch-prod"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-prod
  template:
    metadata:
      labels:
        app: elasticsearch-prod
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
          resources:
            requests:
              cpu: 1000m
              memory: 4Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elastic-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-prod
spec:
  selector:
    app: elasticsearch-prod
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
